# Generated by Django 3.2.8 on 2021-10-23 14:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='pronouns',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.system'),
        ),
        migrations.AlterField(
            model_name='alter',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='alter',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='alter',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='alter',
            name='groups',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='alter',
            name='is_fragment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alter',
            name='pronouns',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='alter',
            name='roles',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='front',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='front',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='front',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
