# Generated by Django 3.2.8 on 2021-10-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211023_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.system'),
        ),
    ]
