# Generated by Django 3.2.8 on 2021-10-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='alter',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
