# Generated by Django 3.2.8 on 2021-10-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211023_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='system',
        ),
        migrations.AddField(
            model_name='system',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
