# Generated by Django 4.0 on 2021-12-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_message_created_at_message_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.CharField(default='https://i.ibb.co/DM0RM4f/default.png', max_length=1024),
        ),
        migrations.AddField(
            model_name='alter',
            name='profile_picture',
            field=models.CharField(default='https://i.ibb.co/DM0RM4f/default.png', max_length=1024),
        ),
    ]
